version: '3.9'
services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
      - common
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=Host(`dev.learnintouch.com`)"
        - "traefik.http.routers.helloworld.entrypoints=web"
#        - "traefik.http.routers.helloworld.entrypoints=websecure"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"
networks:
  common:
    external: true
